version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./ssl:/etc/ssl/custom
    depends_on:
      - db
    environment:
      - APP_NAME=BioNettoyage
      - APP_ENV=local
      - APP_KEY=base64:coFHkG/hMn8vOt8LzQQfhMQgMq6tijejbypLU2cGQ5o=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=bionet_db
      - DB_USERNAME=lucien
      - DB_PASSWORD=Lucknite0710.

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: bionet_db
      MYSQL_USER: lucien
      MYSQL_PASSWORD: Lucknite0710.
      MYSQL_ROOT_PASSWORD: Lucknite0710.
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
