version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - URLROOT=http://localhost:8080

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: bionet_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
